feat: two-fer fixture
exercism/wasm-test-runner pull request #7
Opened 2022-02-22 20:47 UTC by bushidocodes

2022-02-22 21:01 UTC, SleeplessByte commented on package.json
> +    "test": "node --experimental-vm-modules node_modules/jest/bin/jest.js ./*",
You still need the build step!

2022-02-22 21:02 UTC, SleeplessByte commented on package.json
> +    "typescript": "^4.7.0-dev.20220222"
Do you need this? Otherwise I recommend stable.

2022-02-22 21:02 UTC, SleeplessByte commented on pnpm-lock.yaml
> +lockfileVersion: 5.3
Probably want to ignore all other locks (yarn.lock and packa-gelokc.json in the .gitignore) and then list PNPM as the required tool in the readme.

2022-02-22 21:12 UTC, bushidocodes commented on package.json
> +    "typescript": "^4.7.0-dev.20220222"
It seems so. If I set the tsconfig `compilerOptions.module` options to generate ESM modules (either `NodeNext` or `Node12`), a log pops up saying that I need to use the Nightly release of the TypeScript compiler. `ts-jest` also emits a warning saying Nightly is unsupported, but it seems to sort of work. :laughing:

2022-02-22 21:13 UTC, bushidocodes commented on pnpm-lock.yaml
> +lockfileVersion: 5.3
Yeah, I've got multiple lockfiles going. Sheesh.

2022-02-22 21:15 UTC, SleeplessByte commented on package.json
> +    "typescript": "^4.7.0-dev.20220222"
According to https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm you may be able to do it with less, but oh well. 4.7.0 will be out soon enough!

2022-02-23 07:24 UTC, ErikSchierboom approved these changes

2022-02-23 07:29 UTC, ErikSchierboom approved these changes
Great job! My only suggestion would be to add tests that verify the contents of the produced `results.json` files. You have all these fixtures that are really useful, but it looks like you don't yet verify the produced `results.json` files. This would give you an even higher degree of confidence in the correct working of the test runner. See this repo for an example: https://github.com/exercism/prolog-test-runner/blob/main/tests/example-empty-file/expected_results.json

2022-02-23 07:29 UTC, ErikSchierboom commented on .gitignore
> +packa-gelokc.json
```suggestion
package-lock.json
```

Or was this intentional?

2022-02-23 10:22 UTC, ErikSchierboom requested changes

2022-02-23 10:22 UTC, ErikSchierboom commented on Dockerfile
> +rm -rf /var/lib/apt/lists/*
You're missing the `\` characters here, which cause the dockerfile to not build

2022-02-23 10:22 UTC, ErikSchierboom commented on Dockerfile
> +pnpm install --production
You're missing the `\` characters here, which cause the dockerfile to not build

2022-02-23 13:46 UTC, bushidocodes commented on package.json
> +    "typescript": "^4.7.0-dev.20220222"
It does seem that I was able to go back to stable with `ES2020`. Still hitting some issues, but a bunch of problems seemed to go away by reverting to stable!

2022-02-23 20:55 UTC, SleeplessByte commented
@ErikSchierboom since merging this is pretty safe if it doesn't work, I'm just gonna do that and we can solve any issues tomorrow 👯

2022-02-23 20:55 UTC, SleeplessByte approved these changes

2022-02-23 20:56 UTC, merged

2022-02-24 06:15 UTC, ErikSchierboom commented
I've just enabled the pushing to dockerhub. For the production servers, we need to update terraform, for which I've created [this PR](https://github.com/exercism/terraform/pull/68). Once that is merged and @iHiD has given this repo access to the dockerhub and ECR secrets, we can re-run the deploy workflow.